### ISSUE TITLE
"comment" command throws 403 error 

### ISSUE THREAD

**Issue by HosseinAgha** [rx-ts/changesets-gitlab#24]
I use a maintainer personal access token with full API and Repository access.  
After running the commit command I get:   
```
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (./node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  description: '403 Forbidden'
}

```

**Comment by HosseinAgha** [comment]
I just found the issue and fixed it in #23
